<script>
  import { tick } from 'svelte';
  import ExampleCarousel from './lib/ExampleCarousel.svelte';
  import ProjectileChallenge from './lib/ProjectileChallenge.svelte';
  import RelationshipLab from './lib/components/RelationshipLab.svelte';
  import { onDestroy } from 'svelte';
  import { generateLevel, sample, subjectMismatch, ACCEPTED_EXTENSIONS, MAX_UPLOAD_MB } from './lib/generate';
  let view='home', step=1, name='',level='',year='',school='',profileError='',subject='',course='',selectedFile=null,error='',fileInput,generating=false,outcome=null,pending=null,loadingStep=0,loadingTimer;
  const loadingMessages=['Reading your material…','Designing your challenges…','Making sure every challenge can be won…'];
  const levelGuide=[['Middle school','Whole numbers and generous targets.'],['High school','One decimal place, and the formula by name.'],['College','Your course’s own notation and tighter targets.']];
  onDestroy(()=>clearInterval(loadingTimer));
  const years={'Middle school':['6th grade','7th grade','8th grade'],'High school':['9th grade','10th grade','11th grade','12th grade'],'College':['First year','Second year','Third year','Fourth year','Graduate']};
  function setLevel(v){if(level!==v){level=v;year=''}profileError=''}
  function submitProfile(){if(!level){profileError='Choose where you are in school.';return}profileError='';step=2}
  async function home(anchor){view='home';await tick();if(anchor)document.getElementById(anchor)?.scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})}
  function start(){view='flow';step=1;window.scrollTo(0,0)}
  function choose(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!ACCEPTED_EXTENSIONS.includes(ext)||file.size>MAX_UPLOAD_MB*1024*1024){error=`Choose a PDF or text file under ${MAX_UPLOAD_MB} MB.`;return}selectedFile=file;error=''}
  function drop(e){e.preventDefault();choose(e.dataTransfer.files[0])}
  async function continueUpload(){if(!subject){error='Choose a subject first.';return}error='';generating=true;loadingStep=0;loadingTimer=setInterval(()=>loadingStep=Math.min(loadingStep+1,loadingMessages.length-1),3500);const result=await generateLevel({file:selectedFile,subject,course,schoolLevel:level});clearInterval(loadingTimer);generating=false;if(result.kind==='file-error'){error=result.message;return}if(result.kind==='level'&&subjectMismatch(subject,result)){pending=result;view='mismatch';window.scrollTo(0,0);return}outcome=result;view=result.kind==='unfit'?'unfit':'lab';window.scrollTo(0,0)}
  function continueAsDetected(){const detected=pending.level.detectedSubject;outcome={...pending,level:{...pending.level,subject:detected,courseLabel:''}};pending=null;view='lab';window.scrollTo(0,0)}
  function playSample(){outcome=sample(subject,'This chapter doesn’t have a relationship to explore.');view='lab';window.scrollTo(0,0)}
  function anotherChapter(){view='flow';step=2;selectedFile=null;outcome=null;pending=null;error='';window.scrollTo(0,0)}
</script>
<svelte:head><title>{view==='home'?'HyperPlay · Learn by exploring':view==='lab'&&outcome?`${outcome.level.concept} · HyperPlay`:'Get started · HyperPlay'}</title></svelte:head>
<header><a class="brand" href="#home" on:click|preventDefault={()=>home()} aria-label="HyperPlay home"><span class="brandmark" aria-hidden="true"></span><span>Hyper<b>Play</b></span></a><nav class="site-nav" aria-label="Main navigation"><a href="#home" on:click|preventDefault={()=>home()}>Home</a><a href="#how" on:click|preventDefault={()=>home('how')}>How it works</a><a href="#demo" on:click|preventDefault={()=>home('demo')}>Demo</a></nav>{#if view==='home'}<button class="primary nav-cta" type="button" on:click={start}>Get started</button>{/if}</header>
{#if view==='home'}
<main id="home" class="landing">
  <section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="eyebrow">A new way to understand what you study</div><h1 id="hero-title">Turn your study materials into something you can <em>play with.</em></h1><p>Explore the ideas in your course material through interactive simulations and short challenges.</p><div class="hero-actions"><a class="primary link-button" href="#demo">Try the live demo</a><button class="secondary" type="button" on:click={start}>Upload your study material →</button></div></div><ExampleCarousel/></section>
  <section id="how" class="how-block" aria-labelledby="how-title"><div class="section-heading"><div><div class="eyebrow">HOW IT WORKS</div><h2 id="how-title">Learn your material interactively.</h2></div><p>HyperPlay uses your course and level as context, then turns a key idea into something you can test.</p></div><div class="how-grid"><article><span class="step-icon">01</span><h3>Upload your study material</h3><p>Choose your course and add a PDF, notes, or slides.</p></article><article><span class="step-icon green-icon">02</span><h3>Understand the idea</h3><p>See the concept, its rule, and what each variable means before you try it.</p></article><article><span class="step-icon amber-icon">03</span><h3>Try it yourself</h3><p>Change a variable, predict the outcome, then run and compare attempts.</p></article></div></section>
  <section id="demo" class="demo-block" aria-labelledby="demo-title"><div class="section-heading"><div><div class="eyebrow">LIVE SAMPLE · PHYSICS</div><h2 id="demo-title">Don’t just read the formula. Test it.</h2></div><p>Adjust the launch and watch how the same concept behaves. This sample runs right here in your browser.</p></div><ProjectileChallenge/></section>
  <section class="closing"><div><h2>Ready to play with what you’re studying?</h2><p>Upload your study material and get your first experiment in under a minute.</p></div><button class="primary" type="button" on:click={start}>Upload your study material →</button></section>
</main>
{:else if view==='flow'}
<main class="shell" id="flow"><div class="topline"><div class="eyebrow">Make learning yours</div><div class="steps" aria-label="Setup progress"><span class:active={step===1} class:done={step===2}><span class="step-dot">{step===2?'✓':'1'}</span> About you</span><span class="connector"></span><span class:active={step===2}><span class="step-dot">2</span> Your material</span></div></div><div class="layout"><section class="panel">
{#if step===1}<button class="back" type="button" on:click={()=>home()}>← Back to home</button><h1>Let’s make this your learning space.</h1><p class="lead">A little context helps HyperPlay shape a chapter for the level you’re studying.</p><form on:submit|preventDefault={submitProfile}><div class="field"><label for="name">What should we call you?</label><input id="name" type="text" placeholder="Your first name" maxlength="40" autocomplete="given-name" required bind:value={name}/></div><div class="field"><span class="field-label">Where are you in school?</span><div class="choice-row" role="group" aria-label="Education level">{#each Object.keys(years) as option}<button class="choice" type="button" aria-pressed={level===option} on:click={()=>setLevel(option)}>{option}</button>{/each}</div></div><div class="dual"><div class="field"><label for="year">Grade or year</label><select id="year" required disabled={!level} bind:value={year}><option value="" disabled>{level?'Choose your grade or year':'Choose your level first'}</option>{#each years[level] ?? [] as y}<option value={y}>{y}</option>{/each}</select></div><div class="field"><label for="school">School <span class="optional">(optional)</span></label><input id="school" type="text" placeholder="Your school" maxlength="80" bind:value={school}/></div></div>{#if profileError}<p class="error" role="alert">{profileError}</p>{/if}<div class="button-row"><span class="quiet">About 20 seconds to set up</span><button class="primary" type="submit">Continue →</button></div></form>
{:else}<button class="back" type="button" on:click={()=>step=1}>← Back to profile</button><h1>What are we learning, {name.trim().split(/\s+/)[0]}?</h1><p class="lead">Choose the course, then add the chapter or notes you want to explore.</p><div class="dual"><div class="field"><label for="subject">Subject</label><select id="subject" bind:value={subject}><option value="">Choose a subject</option>{#each ['Physics','Biology','Math','Chemistry','Computer science','History','Other'] as v}<option>{v}</option>{/each}</select></div><div class="field"><label for="course">Course</label><input id="course" type="text" placeholder="e.g. AP Physics 1" maxlength="100" bind:value={course}/></div></div><div class="field"><span class="field-label">Your learning material</span><div class="drop" role="button" tabindex="0" on:click={()=>fileInput.click()} on:keydown={(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fileInput.click()}}} on:dragover|preventDefault on:drop={drop}><span class="upload-symbol" aria-hidden="true">↑</span><strong>Drop a file here, or browse</strong><p>PDF or text file · up to {MAX_UPLOAD_MB} MB</p><span class="outline">Choose a file</span></div><input class="hidden" bind:this={fileInput} type="file" accept=".pdf,.txt" aria-label="Choose learning material" on:change={(e)=>choose(e.currentTarget.files[0])}/>{#if selectedFile}<div class="files"><span class="file-icon">{selectedFile.name.split('.').pop().toUpperCase()}</span><div><div class="file-name">{selectedFile.name}</div><div class="file-sub">{(selectedFile.size/1024/1024).toFixed(1)} MB</div></div><button class="remove" type="button" aria-label="Remove selected file" on:click={()=>{selectedFile=null;fileInput.value=''}}>×</button></div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</div><div class="upload-actions"><span class="quiet">{level} · {year}</span><button class="primary" type="button" disabled={!selectedFile||generating} on:click={continueUpload}>{generating?'Building your level…':'Build my level →'}</button></div>{#if generating}<div class="building" role="status" aria-live="polite"><div class="building-bar" aria-hidden="true"><i></i></div><span>{loadingMessages[loadingStep]}</span></div>{/if}<p class="privacy"><span aria-hidden="true">🔒</span> Your material stays private. It’s only used to build your experiment, and HyperPlay never saves it.</p>{/if}
</section><aside class="aside" aria-label="{step===1?'Why we ask':'What works best'}"><div>{#if step===1}<div class="eyebrow">Why we ask</div><h2>Your level shapes the challenge.</h2><p>HyperPlay adjusts every experiment to where you are, so it’s never too easy or out of reach.</p><ul class="guide">{#each levelGuide as [label,text]}<li class:current={level===label}><strong>{label}</strong><span>{text}</span></li>{/each}</ul>{:else}<div class="eyebrow">What works best</div><h2>Material with a formula, a rate, or a graph.</h2><p>Chapters on gas laws, population growth, compound interest, motion, or algorithm speed make great experiments.</p><div class="ladder-title">What you’ll get</div><ol class="ladder"><li><span>1</span><div><strong>Change one thing</strong><small>See the first idea on its own.</small></div></li><li><span>2</span><div><strong>Change the other</strong><small>See the second idea on its own.</small></div></li><li><span>3</span><div><strong>Put them together</strong><small>Find more than one way to hit the goal.</small></div></li></ol>{/if}</div><div class="aside-foot"><span>✓</span> Made for understanding, one concept at a time.</div></aside></div></main>
{:else if view==='lab'&&outcome}
<main class="shell lab-shell"><button class="back" type="button" on:click={anotherChapter}>← Try another chapter</button><RelationshipLab level={outcome.level} source={outcome.source} notice={outcome.notice} onNewChapter={anotherChapter}/></main>
{:else if view==='mismatch'&&pending}
<main class="shell"><section class="panel unfit"><button class="back" type="button" on:click={anotherChapter}>← Back</button><div class="eyebrow">Quick check</div><h1>This looks like a {pending.level.detectedSubject} chapter.</h1><p class="lead">You chose <strong>{subject}</strong>, but your file reads like <strong>{pending.level.detectedSubject}</strong>. HyperPlay built an experiment about <strong>{pending.level.concept}</strong>.</p><div class="unfit-actions"><button class="secondary" type="button" on:click={anotherChapter}>Choose a different file</button><button class="primary" type="button" on:click={continueAsDetected}>Continue as {pending.level.detectedSubject} →</button></div></section></main>
{:else if view==='unfit'&&outcome}
<main class="shell"><section class="panel unfit"><button class="back" type="button" on:click={anotherChapter}>← Back</button><div class="eyebrow">This chapter doesn’t fit yet</div><h1>We couldn’t find a relationship to play with.</h1><p class="lead">{outcome.reason}</p><p class="lead"><strong>What works best:</strong> {outcome.suggestion}</p><p class="quiet">HyperPlay builds experiments from chapters with a formula, a rate, or a graph.</p><div class="unfit-actions"><button class="secondary" type="button" on:click={playSample}>Play a sample level</button><button class="primary" type="button" on:click={anotherChapter}>Try another file →</button></div></section></main>
{/if}
