<script>
  import { tick } from 'svelte';
  import ExampleCarousel from './lib/ExampleCarousel.svelte';
  import ProjectileChallenge from './lib/ProjectileChallenge.svelte';
  let view='home', step=1, name='',level='High school',year='11th grade',school='',subject='',course='',selectedFile=null,error='',notice=false,fileInput;
  const years={'Middle school':['6th grade','7th grade','8th grade'],'High school':['9th grade','10th grade','11th grade','12th grade'],'College':['First year','Second year','Third year','Fourth year','Graduate']};
  function setLevel(v){level=v;year=v==='High school'?'11th grade':v==='College'?'Third year':'7th grade'}
  async function home(anchor){view='home';await tick();if(anchor)document.getElementById(anchor)?.scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})}
  function start(){view='flow';step=1;window.scrollTo(0,0)}
  function choose(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['pdf','ppt','pptx','doc','docx','txt'].includes(ext)||file.size>50*1024*1024){error='Choose a PDF, slides, Word document, or text file under 50 MB.';return}selectedFile=file;error='';notice=false}
  function drop(e){e.preventDefault();choose(e.dataTransfer.files[0])}
  function continueUpload(){if(!subject){error='Choose a subject first.';return}error='';notice=true}
</script>
<svelte:head><title>{view==='home'?'HyperPlay · Learn by exploring':'Get started · HyperPlay'}</title></svelte:head>
<header><a class="brand" href="#home" on:click|preventDefault={()=>home()} aria-label="HyperPlay home"><span class="brandmark" aria-hidden="true"></span><span>Hyper<b>Play</b></span></a><nav class="site-nav" aria-label="Main navigation"><a href="#home" on:click|preventDefault={()=>home()}>Home</a><a href="#how" on:click|preventDefault={()=>home('how')}>How it works</a><a href="#demo" on:click|preventDefault={()=>home('demo')}>Demo</a></nav><button class="primary nav-cta" type="button" on:click={start}>Get started</button></header>
{#if view==='home'}
<main id="home" class="landing">
  <section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="eyebrow">A new way to understand what you study</div><h1 id="hero-title">Turn a textbook chapter into something you can <em>play with.</em></h1><p>Explore the ideas in your course material through interactive simulations and short challenges. Start with a sample and see what changes when you change the variables.</p><div class="hero-actions"><a class="primary link-button" href="#demo">Try the live demo →</a><button class="secondary" type="button" on:click={start}>Upload your material</button></div><div class="hero-note">No account needed to try the sample</div></div><ExampleCarousel/></section>
  <section id="how" class="how-block" aria-labelledby="how-title"><div class="section-heading"><div><div class="eyebrow">HOW IT WORKS</div><h2 id="how-title">Your material becomes the experiment.</h2></div><p>HyperPlay uses your course and level as context, then turns a key idea into something you can test.</p></div><div class="how-grid"><article><span class="step-icon">01</span><h3>Bring a chapter</h3><p>Choose your course and add a PDF, notes, or slides.</p></article><article><span class="step-icon green-icon">02</span><h3>Understand the idea</h3><p>See the concept, its rule, and what each variable means before you try it.</p></article><article><span class="step-icon amber-icon">03</span><h3>Try it yourself</h3><p>Change a variable, predict the outcome, then run and compare attempts.</p></article></div></section>
  <section id="demo" class="demo-block" aria-labelledby="demo-title"><div class="section-heading"><div><div class="eyebrow">LIVE SAMPLE · PHYSICS</div><h2 id="demo-title">Don’t just read the formula. Test it.</h2></div><p>Adjust the launch and watch how the same concept behaves. This sample runs right here in your browser.</p></div><ProjectileChallenge/></section>
  <section class="closing"><div><h2>Ready to try your own chapter?</h2><p>Tell HyperPlay what you’re studying, then add your material.</p></div><button class="primary" type="button" on:click={start}>Get started →</button></section>
</main>
{:else}
<main class="shell" id="flow"><div class="topline"><div class="eyebrow">Make learning yours</div><div class="steps" aria-label="Setup progress"><span class:active={step===1} class:done={step===2}><span class="step-dot">{step===2?'✓':'1'}</span> About you</span><span class="connector"></span><span class:active={step===2}><span class="step-dot">2</span> Your material</span></div></div><div class="layout"><section class="panel">
{#if step===1}<button class="back" type="button" on:click={()=>home()}>← Back to home</button><h1>Let’s make this your learning space.</h1><p class="lead">A little context helps HyperPlay shape a chapter for the level you’re studying.</p><form on:submit|preventDefault={()=>step=2}><div class="field"><label for="name">What should we call you?</label><input id="name" type="text" placeholder="Your first name" maxlength="40" autocomplete="given-name" required bind:value={name}/></div><div class="field"><span class="field-label">Where are you in school?</span><div class="choice-row" role="group" aria-label="Education level">{#each Object.keys(years) as option}<button class="choice" type="button" aria-pressed={level===option} on:click={()=>setLevel(option)}>{option}</button>{/each}</div></div><div class="dual"><div class="field"><label for="year">Grade or year</label><select id="year" required bind:value={year}>{#each years[level] as y}<option value={y}>{y}</option>{/each}</select></div><div class="field"><label for="school">School <span class="optional">(optional)</span></label><input id="school" type="text" placeholder="Your school" maxlength="80" bind:value={school}/></div></div><div class="button-row"><span class="quiet">About 20 seconds to set up</span><button class="primary" type="submit">Continue →</button></div></form>
{:else}<button class="back" type="button" on:click={()=>step=1}>← Back to profile</button><h1>What are we learning, {name.trim().split(/\s+/)[0]}?</h1><p class="lead">Choose the course, then add the chapter or notes you want to explore.</p><div class="dual"><div class="field"><label for="subject">Subject</label><select id="subject" bind:value={subject}><option value="">Choose a subject</option>{#each ['Physics','Biology','Math','Chemistry','Computer science','History','Other'] as v}<option>{v}</option>{/each}</select></div><div class="field"><label for="course">Course</label><input id="course" type="text" placeholder="e.g. AP Physics 1" maxlength="100" bind:value={course}/></div></div><div class="field"><span class="field-label">Your learning material</span><div class="drop" role="button" tabindex="0" on:click={()=>fileInput.click()} on:keydown={(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fileInput.click()}}} on:dragover|preventDefault on:drop={drop}><span class="upload-symbol" aria-hidden="true">↑</span><strong>Drop a file here, or browse</strong><p>PDF, slides, Word document, or text · up to 50 MB</p><span class="outline">Choose a file</span></div><input class="hidden" bind:this={fileInput} type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.txt" aria-label="Choose learning material" on:change={(e)=>choose(e.currentTarget.files[0])}/>{#if selectedFile}<div class="files"><span class="file-icon">{selectedFile.name.split('.').pop().toUpperCase()}</span><div><div class="file-name">{selectedFile.name}</div><div class="file-sub">{(selectedFile.size/1024/1024).toFixed(1)} MB</div></div><button class="remove" type="button" aria-label="Remove selected file" on:click={()=>{selectedFile=null;fileInput.value='';notice=false}}>×</button></div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</div><div class="upload-actions"><span class="quiet">{level} · {year}</span><button class="primary" type="button" disabled={!selectedFile} on:click={continueUpload}>Continue →</button></div>{#if notice}<div class="notice" role="status">This is a UI demo through file selection. Generation will connect to your team’s backend and model.</div>{/if}<p class="privacy">In this preview, your selected file stays in your browser and is not uploaded.</p>{/if}
</section><aside class="aside" aria-label="HyperPlay concept preview"><div><div class="eyebrow">A glimpse of what comes next</div><h2>From reading to exploring.</h2><p>Course material becomes a hands-on experience built around the concepts you need to learn.</p><div class="concept-card"><div class="card-top"><span>PHYSICS · SAMPLE EXPERIENCE</span><span>Interactive</span></div><h3>What changes the path?</h3><p>Adjust the launch angle. Watch the trajectory respond.</p><div class="play-surface" aria-hidden="true"><span class="axis"></span><span class="arc"></span><span class="ball"></span><span class="range"></span></div><div class="legend"><i></i> Launch angle <strong>45°</strong></div></div></div><div class="aside-foot"><span>✓</span> Made for understanding, one concept at a time.</div></aside></div></main>
{/if}
